import pytest
import requests
from pathlib import Path
from conftest import MODELS_DIR, REFERENCE_GCODE_DIR, ASSERT_PARAMS, parse_gcode_header

BED_TYPE = "Textured PEI Plate"


def reference_gcode(prefix: str) -> bytes:
    matches = list(REFERENCE_GCODE_DIR.glob(f"{prefix}_PLA*.gcode"))
    assert matches, f"No reference GCODE found for prefix '{prefix}' in {REFERENCE_GCODE_DIR}"
    return matches[0].read_bytes()


def slice_model(api, core_profiles, model_name, *, orient=False, bed_type=BED_TYPE):
    data = {
        "printer": core_profiles["printer"],
        "process": core_profiles["process"],
        "filament": core_profiles["filament"],
        "bed_type": bed_type,
    }
    if orient:
        data["orient"] = "1"
    with open(MODELS_DIR / model_name, "rb") as f:
        return requests.post(
            f"{api}/api/slice",
            files={"model": (model_name, f, "application/octet-stream")},
            data=data,
        )


# --- Health / status ---

def test_health(api):
    r = requests.get(f"{api}/api/health")
    assert r.status_code == 200
    body = r.json()
    assert body["status"] == "ok"
    assert body["slicer_found"] is True


def test_slice_status_idle(api):
    r = requests.get(f"{api}/api/slice/status")
    assert r.status_code == 200
    assert r.json()["busy"] is False


# --- Happy path ---

def test_slice_cube_matches_gui_reference(api, core_profiles):
    r = slice_model(api, core_profiles, "cube_20mm.stl")
    assert r.status_code == 200, f"Slice failed: {r.text}"
    assert r.headers["content-type"] == "application/octet-stream"
    assert "X-Slice-Time-Seconds" in r.headers

    api_params = parse_gcode_header(r.content)
    ref_params = parse_gcode_header(reference_gcode("cube_20mm"))

    mismatches = [
        f"  {k}: API={api_params.get(k)!r}  REF={ref_params.get(k)!r}"
        for k in ASSERT_PARAMS
        if api_params.get(k) != ref_params.get(k)
    ]
    assert not mismatches, "GCODE header differs from GUI reference:\n" + "\n".join(mismatches)


def test_slice_needs_orient_matches_gui_reference(api, core_profiles):
    r = slice_model(api, core_profiles, "needs_orient.stl", orient=True)
    assert r.status_code == 200, f"Slice failed: {r.text}"

    api_params = parse_gcode_header(r.content)
    ref_params = parse_gcode_header(reference_gcode("needs_orient"))

    mismatches = [
        f"  {k}: API={api_params.get(k)!r}  REF={ref_params.get(k)!r}"
        for k in ASSERT_PARAMS
        if api_params.get(k) != ref_params.get(k)
    ]
    assert not mismatches, "GCODE header differs from GUI reference:\n" + "\n".join(mismatches)


def test_slice_produces_valid_gcode(api, core_profiles):
    r = slice_model(api, core_profiles, "cube_20mm.stl")
    assert r.status_code == 200
    text = r.content.decode("utf-8", errors="replace")
    assert "; generated by OrcaSlicer" in text
    assert "G28" in text  # homing command present


def test_slice_response_has_gcode_filename(api, core_profiles):
    r = slice_model(api, core_profiles, "cube_20mm.stl")
    assert r.status_code == 200
    disposition = r.headers.get("content-disposition", "")
    assert ".gcode" in disposition


def test_slice_3mf_accepted(api, core_profiles):
    # 3MF is a zip — create a minimal one to confirm the API accepts the extension.
    # Full slicing is out of scope here; we just check the API doesn't reject on ext.
    import zipfile, io
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("[Content_Types].xml", "")
    buf.seek(0)
    r = requests.post(
        f"{api}/api/slice",
        files={"model": ("model.3mf", buf, "application/octet-stream")},
        data={
            "printer": core_profiles["printer"],
            "process": core_profiles["process"],
            "filament": core_profiles["filament"],
        },
    )
    # Not 400 (extension rejected) — slicer may fail on the empty zip, but that's a 500
    assert r.status_code != 400


# --- Print option overrides ---

def test_slice_layer_height_override_reflected_in_gcode(api, core_profiles):
    r = slice_model(api, core_profiles, "cube_20mm.stl")
    baseline_layer_height = parse_gcode_header(r.content).get("layer_height")

    data = {
        "printer": core_profiles["printer"],
        "process": core_profiles["process"],
        "filament": core_profiles["filament"],
        "bed_type": BED_TYPE,
        "layer_height": "0.28",
    }
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data=data,
        )
    assert r.status_code == 200, f"Slice failed: {r.text}"
    overridden_layer_height = parse_gcode_header(r.content).get("layer_height")
    assert overridden_layer_height == "0.28"
    assert overridden_layer_height != baseline_layer_height


def test_slice_invalid_layer_height_returns_400(api, core_profiles):
    data = {
        "printer": core_profiles["printer"],
        "process": core_profiles["process"],
        "filament": core_profiles["filament"],
        "layer_height": "not-a-number",
    }
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data=data,
        )
    assert r.status_code == 400


def test_slice_out_of_range_fill_density_returns_400(api, core_profiles):
    data = {
        "printer": core_profiles["printer"],
        "process": core_profiles["process"],
        "filament": core_profiles["filament"],
        "fill_density": "150",
    }
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data=data,
        )
    assert r.status_code == 400


def test_slice_overrides_do_not_mutate_stored_profile(api, core_profiles):
    before = requests.get(f"{api}/api/profiles/process/{core_profiles['process']}").content
    slice_model(api, core_profiles, "cube_20mm.stl")
    data = {
        "printer": core_profiles["printer"],
        "process": core_profiles["process"],
        "filament": core_profiles["filament"],
        "layer_height": "0.3",
        "fill_density": "80",
        "enable_support": "1",
    }
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data=data,
        )
    after = requests.get(f"{api}/api/profiles/process/{core_profiles['process']}").content
    assert before == after


# --- Error cases ---

def test_slice_missing_model_field_returns_400(api, core_profiles):
    r = requests.post(
        f"{api}/api/slice",
        data={
            "printer": core_profiles["printer"],
            "process": core_profiles["process"],
            "filament": core_profiles["filament"],
        },
    )
    assert r.status_code == 400


def test_slice_unsupported_model_type_returns_400(api, core_profiles):
    r = requests.post(
        f"{api}/api/slice",
        files={"model": ("model.obj", b"v 0 0 0\n", "application/octet-stream")},
        data={
            "printer": core_profiles["printer"],
            "process": core_profiles["process"],
            "filament": core_profiles["filament"],
        },
    )
    assert r.status_code == 400


def test_slice_missing_all_profile_params_returns_400(api):
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
        )
    assert r.status_code == 400


def test_slice_nonexistent_profiles_returns_404(api):
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data={
                "printer": "no-such-printer",
                "process": "no-such-process",
                "filament": "no-such-filament",
            },
        )
    assert r.status_code == 404


def test_slice_partial_profiles_returns_400(api, core_profiles):
    with open(MODELS_DIR / "cube_20mm.stl", "rb") as f:
        r = requests.post(
            f"{api}/api/slice",
            files={"model": ("cube_20mm.stl", f, "application/octet-stream")},
            data={"printer": core_profiles["printer"]},
        )
    assert r.status_code == 400
